# Generated by Django 2.1.3 on 2018-11-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cloth', 'Cloth'), ('stationary', 'Stationary'), ('grocery', 'Grocery'), ('vegetables', 'Vegetables')], max_length=1)),
                ('type', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=30)),
                ('product_info', models.CharField(max_length=1000)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
    ]
