# Generated by Django 2.1.3 on 2018-11-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
