# Generated by Django 2.1.3 on 2018-11-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181122_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='product_info',
            field=models.CharField(max_length=100),
        ),
    ]
