# Generated by Django 2.1.3 on 2018-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20181122_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_data',
            name='image_link',
            field=models.ImageField(default='/media/maggie.jpg', max_length=200, upload_to=''),
            preserve_default=False,
        ),
    ]
