# Generated by Django 2.1.3 on 2018-12-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20181228_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attributes',
            name='attr',
            field=models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('weight', 'Weight'), ('others', 'Others')], max_length=20),
        ),
    ]
