# Generated by Django 2.1.3 on 2018-12-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20181228_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_data',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
