# Generated by Django 2.1.3 on 2018-12-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_data_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_data',
            options={'verbose_name': 'users'},
        ),
    ]
