# Generated by Django 2.1.3 on 2018-12-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20181231_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_data',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelTable(
            name='product_data',
            table='Products',
        ),
    ]
