# Generated by Django 2.1.3 on 2019-01-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20181231_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='category',
            field=models.CharField(choices=[('cloth', 'Cloth'), ('stationary', 'Stationary'), ('grocery', 'Grocery'), ('vegetables', 'Vegetables'), (models.CharField(max_length=100), 'Others')], max_length=20),
        ),
    ]
