# Generated by Django 2.1.3 on 2019-01-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190103_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='category',
            field=models.CharField(choices=[('cloth', 'Cloth'), ('stationary', 'Stationary'), ('grocery', 'Grocery'), ('vegetables', 'Vegetables')], max_length=20),
        ),
    ]
