# Generated by Django 2.1.5 on 2019-01-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='number_of_items',
        ),
    ]
