# Generated by Django 2.1.5 on 2019-01-30 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190103_1233'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_auto_20190103_1401'),
        ('user_basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_product_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='number_of_items',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
