# Generated by Django 2.1.5 on 2019-01-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_basket', '0002_auto_20190130_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_product',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='basket_product_shop',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='userprofile',
        ),
        migrations.DeleteModel(
            name='basket',
        ),
    ]
