# Generated by Django 2.1.5 on 2019-01-30 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0008_auto_20190103_1401'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_auto_20190103_1233'),
        ('user_basket', '0003_auto_20190130_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.IntegerField()),
                ('basket_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_data')),
                ('basket_product_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Basket',
                'db_table': 'User_Basket',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
