# Generated by Django 2.1.5 on 2019-01-30 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190103_1233'),
        ('shop', '0008_auto_20190103_1401'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_basket', '0004_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='basket_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.IntegerField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='basket',
            name='basket_product',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='basket_product_shop',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='number_of_items',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket_product',
            name='basket_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_basket.basket'),
        ),
        migrations.AddField(
            model_name='basket_product',
            name='basket_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_data'),
        ),
        migrations.AddField(
            model_name='basket_product',
            name='basket_product_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
    ]
