# Generated by Django 2.1.5 on 2019-01-30 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190103_1401'),
        ('user_basket', '0006_auto_20190130_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_product_shop',
        ),
        migrations.AddField(
            model_name='basket_product',
            name='basket_product_shop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
            preserve_default=False,
        ),
    ]
