# Generated by Django 2.1.5 on 2019-01-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_basket', '0007_auto_20190130_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket_product',
            old_name='number_of_items',
            new_name='quantity',
        ),
    ]
