# Generated by Django 2.1.3 on 2019-02-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_basket', '0008_auto_20190130_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
