# Generated by Django 2.1.3 on 2019-02-05 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_basket', '0009_auto_20190201_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_product',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
