# Generated by Django 2.1.3 on 2018-12-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_product_data_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('comment', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=100, null=True)),
                ('address_State', models.CharField(choices=[('BR', 'Bihar'), ('JH', 'Jharkhand')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('Shop_icon', models.ImageField(upload_to='')),
                ('number_of_reviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_data'),
        ),
    ]
