# Generated by Django 2.1.3 on 2018-12-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Shop_icon_2',
            field=models.ImageField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
