# Generated by Django 2.1.3 on 2018-12-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181230_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Shop_icon_2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
