# Generated by Django 2.1.3 on 2019-01-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190103_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Shop_icon',
            field=models.ImageField(upload_to='', verbose_name='Shop Photo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Shop_icon_2',
            field=models.ImageField(null=True, upload_to='', verbose_name='Another Shop Photo'),
        ),
    ]
