# Generated by Django 2.1.3 on 2019-02-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_address',
        ),
    ]
