# Generated by Django 2.1.3 on 2019-02-05 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_delete_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField()),
                ('city', models.CharField(choices=[('Patna', 'Patna'), ('Delhi', 'Delhi')], max_length=20)),
                ('area', models.CharField(max_length=50, null=True)),
                ('complete_address', models.CharField(max_length=200, null=True)),
                ('PinCode', models.IntegerField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('gps', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
