# Generated by Django 2.1.3 on 2019-02-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
