# Generated by Django 2.1.4 on 2019-01-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_order_products',
            options={'verbose_name': 'Ordered Products'},
        ),
        migrations.AlterField(
            model_name='user_order',
            name='ordered_from_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Shop', verbose_name='Sold by'),
        ),
        migrations.AlterModelTable(
            name='user_order_products',
            table='Ordered Products',
        ),
    ]
