# Generated by Django 2.1.4 on 2019-01-05 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190105_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_order',
            options={'verbose_name': 'User Order'},
        ),
        migrations.AddField(
            model_name='user_order_products',
            name='for_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.user_order'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user_order',
            table='User Order',
        ),
    ]
