# Generated by Django 2.1.4 on 2019-01-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190105_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
