# Generated by Django 2.1.4 on 2019-01-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_user_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_order',
            old_name='total_price',
            new_name='total_amount',
        ),
    ]
