# Generated by Django 2.1.5 on 2019-01-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190127_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_order_products',
            options={'verbose_name': 'Ordered Product', 'verbose_name_plural': 'Ordered Products'},
        ),
        migrations.AlterField(
            model_name='user_order_products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
