# Generated by Django 2.1.5 on 2019-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190127_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order_products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
